name: AWS Check login

on:
  workflow_dispatch:

jobs:
  stop-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ•’ Show current date and time
        run: |
          echo "ğŸ“… Current Date: $(date +'%Y-%m-%d')"
          echo "â° Current Time: $(date +'%H:%M:%S')"
          echo "ğŸŒ Timezone: $(date +'%Z')"

      - name: Set up AWS credentials
        uses: VKalenski/GitHub-Actions-Templates/.github/actions/aws-credentials@main
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-west-3'

      - name: ğŸ”’ Verify identity
        run: aws sts get-caller-identity

      - name: ğŸ“¡ List EC2 instances (running only)
        run: |
          echo "Fetching running EC2 instances..."
          aws ec2 describe-instances \
            --filters "Name=instance-state-name,Values=running" \
            --query "Reservations[].Instances[].InstanceId" \
            --output table

      - name: ğŸ“‚ List S3 buckets
        run: |
          echo "Listing S3 buckets..."
          aws s3 ls

      - name: ğŸ§ª Test AWS CLI version and region
        run: |
          aws --version
          echo "Current region: $(aws configure get region)"