name: System Info Test

on: [push]

jobs:
  system-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # releases v6.0.0

      - name: Show current directory
        run: pwd

      - name: List files
        run: ls -la

      - name: Show environment variables
        run: env

      - name: Simulate build step
        run: echo "Pretend we're building something..."

      - name: Print current date
        run: date
