name: System Info Test

on: [push]

jobs:
  system-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # releases v6.0.1

      - name: Show current directory
        run: pwd

      - name: List files
        run: ls -la

      - name: Show environment variables
        run: env

      - name: Simulate build step
        run: echo "Pretend we're building something..."

      - name: Print current date
        run: date
